name: CI

on:
  workflow_dispatch: ~
  push: ~

jobs:
  build-php-latest:
    name: Build latest PHP

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php-branch:
          - master
#          - PHP-8.3
#          - PHP-8.2
#          - PHP-8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq bison re2c libpq-dev libcurl4-openssl-dev libonig-dev

      - name: Checkout PHP
        uses: actions/checkout@v4
        with:
          repository: php/php-src
          ref: ${{ matrix.php-branch }}
          path: build

      - name: Configure
        working-directory: build
        env:
          PHP_DIR: /opt/${{ matrix.php-branch }}
        run: ../configure.sh

      - name: Build
        working-directory: build
        run: make -j8

      - name: Install
        working-directory: build
        run: sudo make install

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.php-branch }}
          path: /opt/${{ matrix.php-branch }}
          retention-days: 1
