name: PHPUnit

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
  workflow_dispatch:
    inputs:
      run_id:
        description: Workflow run id
        required: true
        type: number

permissions:
  contents: read
  actions: read

jobs:
  test:
    name: PHPUnit tests

    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-branch:
          - master
          - PHP-8.3
          - PHP-8.2
          - PHP-8.1

        phpunit-branch:
          - main
          - 10.5
          - 9.6
          - 8.5

        exclude:
          - phpunit-branch: main
            php-branch: PHP-8.1

    env:
      PHP: /opt/${{ matrix.php-branch }}/bin/php

    steps:
      - name: Install PHP from artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ matrix.php-branch }}
          path: /opt/${{ matrix.php-branch }}
          workflow: ${{ github.event.workflow.id || 'CI' }}
          run_id: ${{ github.event.workflow_run.id || inputs.run_id }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: sebastianbergmann/phpunit
          ref: ${{ matrix.phpunit-branch }}

      - name: Checkout build configuration
        uses: actions/checkout@v4
        with:
          path: build

      - name: Enable PHP and install Composer
        run: build/php-composer.sh

      - name: Install dependencies with Composer
        run: composer install

      - name: Run tests
        run: $PHP ./phpunit --log-junit junit.xml

      - name: Publish report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: 'junit.xml'
          annotate_only: true
