name: PHPUnit

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
  workflow_dispatch:
    inputs:
      run_id:
        description: Workflow run id
        required: true
        type: number

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    name: PHPUnit tests

    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        phpunit-branch:
          - main
          - "12.4"
          - "11.5"
          - "10.5"
          - "9.6"
          - "8.5"

        php-branch:
          - master
          - PHP-8.5
          - PHP-8.4
          - PHP-8.3
          - PHP-8.2
          - PHP-8.1

        php-coverage:
          - pcov
          - xdebug
          - none

        exclude:
          - phpunit-branch: main
            php-branch: PHP-8.1
          - phpunit-branch: main
            php-branch: PHP-8.2
          - phpunit-branch: main
            php-branch: PHP-8.3
          - phpunit-branch: "12.4"
            php-branch: PHP-8.1
          - phpunit-branch: "12.4"
            php-branch: PHP-8.2
          - phpunit-branch: "11.5"
            php-branch: PHP-8.1
          - php-branch: master
            php-coverage: pcov
          - php-branch: master
            php-coverage: xdebug
          - php-branch: PHP-8.5 # not ready yet
            php-coverage: xdebug
          - php-branch: PHP-8.5
            php-coverage: none
          - php-branch: PHP-8.4
            php-coverage: none
          - php-branch: PHP-8.3
            php-coverage: none
          - php-branch: PHP-8.2
            php-coverage: none
          - php-branch: PHP-8.1
            php-coverage: none

          # Build unexpectedly fails, see: https://github.com/sebastianbergmann/phpunit/issues/6128
          - php-branch: PHP-8.2
            php-coverage: xdebug

    env:
      PHP_DIR: /opt/${{ matrix.php-branch }}
      PHP: /opt/${{ matrix.php-branch }}/bin/php

    steps:
      - name: Setup
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq sqlite3 libicu74

      - name: Install PHP from artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          name: ${{ matrix.php-branch }}
          path: /opt/${{ matrix.php-branch }}
          workflow: ${{ github.event.workflow.id || 'CI' }}
          run_id: ${{ github.event.workflow_run.id || inputs.run_id }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: sebastianbergmann/phpunit
          ref: ${{ matrix.phpunit-branch }}

      - name: Checkout build configuration
        uses: actions/checkout@v4
        with:
          path: build

      - name: Enable PHP and install Composer
        run: build/php-setup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies with Composer
        run: $PHP /usr/local/bin/composer install --no-interaction --no-ansi --no-progress

      - name: Install xdebug
        if: matrix.php-coverage == 'xdebug'
        run: |
          $PHP /usr/local/bin/pie install --with-php-config "${PHP_DIR}/bin/php-config" --skip-enable-extension -j 2 xdebug/xdebug
          echo "zend_extension=xdebug.so" >> "${PHP_DIR}/lib/php.ini"
          echo "XDEBUG_MODE=coverage" >> $GITHUB_ENV

      - name: Install pcov
        if: matrix.php-coverage == 'pcov'
        run: |
          $PHP /usr/local/bin/pie install --with-php-config "${PHP_DIR}/bin/php-config" --skip-enable-extension -j 2 pecl/pcov
          echo "extension=pcov.so" >> "${PHP_DIR}/lib/php.ini"

      - name: Run tests
        run: $PHP ./phpunit --log-junit junit-${{ matrix.phpunit-branch }}-${{ matrix.php-branch }}-${{ matrix.php-coverage }}.xml

      - name: Upload test report
        uses: actions/upload-artifact@v4
        if: always() # always run even if the previous step fails
        with:
          name: test-results-${{ matrix.phpunit-branch }}-${{ matrix.php-branch }}-${{ matrix.php-coverage }}
          path: 'junit-*.xml'
          retention-days: 1

  report:
    name: Collect results

    runs-on: ubuntu-24.04

    needs:
      - test

    if: always() && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: sebastianbergmann/phpunit

      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.run_id }}
          name: test-results-.*
          name_is_regexp: true
          if_no_artifact_found: warn
          path: test-results

      - name: Publish Test Report
        uses: mbeccati/test-reporter@phpunit-support
        with:
          name: PHPUnit Test results
          path: '**/junit-*.xml'
          reporter: java-junit
          only-summary: true
